[package]
name = "procem_default"
version = "0.1.0"
edition = "2024"

[dependencies]
procem = { path = "../procem", features = ["alloc"] }
thiserror = { workspace = true }

[lib]
name = "procem_default"
