[package]
name = "assembler"
version = "0.1.0"
edition = "2024"

[dependencies]
emulator_core = {path = "../emulator_core"}
thiserror = {workspace = true}

[lib]
name = "assembler"

[[bin]]
name = "asmc"
path = "src/main.rs"
