[package]
name = "asm_compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
emulator_core = {path = "../emulator_core"}
thiserror = "2.0.12"

[lib]
name = "asm_compiler"

[[bin]]
name = "asmc"
path = "src/main.rs"
